// Opciones predefinidas para conocimientos técnicos

export const OFFICE_SOFTWARE_OPTIONS = [
  'Microsoft Word (procesamiento de texto)',
  'Microsoft Excel (hojas de cálculo avanzadas)',
  'Microsoft PowerPoint (presentaciones)',
  'Microsoft Access',
  'Microsoft Project',
  'Microsoft Visio',
  'Google Docs',
  'Google Sheets (hojas de cálculo en la nube)',
  'Google Slides',
  'Google Forms (creación de formularios en línea)',
  'LibreOffice Writer',
  'LibreOffice Calc',
  'LibreOffice Impress',
  'Adobe Acrobat',
  'Notion',
  'Trello',
  'Asana',
  'Monday.com',
  'Slack',
  'Microsoft Teams',
  'Zoom',
  'Skype for Business',
  'Power BI (análisis y visualización de datos)'
];

export const TECHNICAL_LANGUAGES_OPTIONS = [
  'Inglés',
  'Portugués',
  'Francés',
  'Alemán',
  'Italiano',
  'Chino Mandarín',
  'Japonés',
  'Coreano',
  'Ruso',
  'Árabe',
  'Hebreo',
  'Hindi',
  'Holandés',
  'Sueco',
  'Noruego',
  'Danés',
  'Finlandés',
  'Polaco',
  'Checo',
  'Húngaro'
];

export const DESIGN_SOFTWARE_OPTIONS = [
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe InDesign',
  'Adobe After Effects',
  'Adobe Premiere Pro',
  'Adobe XD',
  'Figma',
  'Sketch',
  'Canva',
  'CorelDRAW',
  'GIMP',
  'Inkscape',
  'Blender',
  '3ds Max',
  'Maya',
  'Cinema 4D',
  'SketchUp',
  'Rhino',
  'KeyShot',
  'V-Ray',
  'AutoCAD (diseño asistido por computadora)',
  'Interpretación de planos técnicos',
  'Autodesk Inventor',
  'Modelado 3D avanzado',
  'Solid Edge',
  'SolidWorks'
];

export const PROGRAMMING_MECHATRONICS_OPTIONS = [
  // Lenguajes de programación
  'Python',
  'Java',
  'JavaScript',
  'TypeScript',
  'C++',
  'C#',
  'C',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Dart',
  'R',
  'MATLAB',
  'Scala',
  'Perl',
  'Shell/Bash',
  'PowerShell',
  
  // Tecnologías web
  'HTML',
  'CSS',
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Express.js',
  'Django',
  'Flask',
  'Laravel',
  'Spring Boot',
  'ASP.NET',
  
  // Bases de datos
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'SQLite',
  'Oracle',
  'SQL Server',
  'Redis',
  'Elasticsearch',
  
  // Herramientas de desarrollo
  'Git',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'AWS',
  'Azure',
  'Google Cloud',
  'Linux',
  'Windows Server',
  
  // Mecatrónica y automatización
  'PLC Siemens',
  'PLC Allen-Bradley',
  'PLC Schneider',
  'PLC Mitsubishi',
  'Programación y configuración de PLCs (Controladores Lógicos Programables)',
  'HMI',
  'SCADA',
  'LabVIEW',
  'Arduino',
  'Raspberry Pi',
  'Microcontroladores',
  'Sensores industriales',
  'Actuadores',
  'Robótica',
  'Visión artificial',
  'Control de procesos',
  
  // Software CAD/CAM
  'AutoCAD',
  'SolidWorks',
  'Inventor',
  'Fusion 360',
  'CATIA',
  'NX',
  'Creo',
  'Mastercam',
  'CNC Programming',
  
  // Simulación y análisis
  'ANSYS',
  'COMSOL',
  'Simulink',
  'Proteus',
  'Multisim',
  'LTspice',
  'PSPICE'
];

export const MANAGEMENT_SYSTEMS_OPTIONS = [
  // ERP Systems
  'SAP',
  'Oracle ERP',
  'Microsoft Dynamics',
  'NetSuite',
  'Odoo',
  'Sage',
  'Infor',
  'Epicor',
  'QAD',
  'IFS',
  
  // CRM Systems
  'Salesforce',
  'HubSpot',
  'Zoho CRM',
  'Pipedrive',
  'Microsoft Dynamics CRM',
  'SugarCRM',
  'Freshworks',
  
  // Gestión de proyectos
  'Jira',
  'Confluence',
  'Azure DevOps',
  'GitLab',
  'Bitbucket',
  'Basecamp',
  'Wrike',
  'Smartsheet',
  
  // Sistemas de calidad y gestión
  'ISO 9001 (Sistemas de gestión de calidad)',
  'ISO 14001 (Sistemas de gestión ambiental)',
  'ISO 45001 (Sistemas de gestión de seguridad y salud ocupacional)',
  'TPM (Total Productive Maintenance - Mantenimiento productivo total)',
  'RCM (Reliability Centered Maintenance - Mantenimiento centrado en confiabilidad)',
  'Six Sigma',
  'Lean Manufacturing',
  'Kaizen',
  'OHSAS 18001',
  
  // Sistemas financieros
  'QuickBooks',
  'Xero',
  'FreshBooks',
  'Wave Accounting',
  'Tango Gestión',
  'Bejerman',
  'Siigo',
  
  // Business Intelligence
  'Power BI',
  'Tableau',
  'QlikView',
  'Looker',
  'Pentaho',
  'IBM Cognos',
  
  // Gestión de inventario
  'WMS',
  'Warehouse Management',
  'Inventory Management',
  'Supply Chain Management',
  'MRP',
  'MRP II'
];

// Opciones para conocimientos complementarios
export const COMPLEMENTARY_KNOWLEDGE_OPTIONS = [
  'Liderazgo de equipos',
  'Gestión de proyectos',
  'Metodologías ágiles (Scrum, Kanban)',
  'Análisis de datos',
  'Inteligencia de negocios',
  'Gestión de la calidad',
  'Auditorías internas',
  'Capacitación y desarrollo',
  'Comunicación efectiva',
  'Negociación',
  'Resolución de conflictos',
  'Pensamiento crítico',
  'Innovación y creatividad',
  'Gestión del tiempo',
  'Trabajo en equipo',
  'Adaptabilidad al cambio',
  'Orientación al cliente',
  'Mejora continua',
  'Benchmarking',
  'Análisis de riesgos',
  'Planificación estratégica',
  'Gestión de recursos humanos',
  'Presupuestación y control financiero',
  'Logística y cadena de suministro',
  'Sostenibilidad empresarial',
  'Responsabilidad social corporativa',
  'Gestión de la innovación',
  'Transformación digital',
  'Gestión del conocimiento',
  'Coaching y mentoring'
];